# Copyright 2025 Keisuke Tominaga a.k.a soundTricker
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ppp
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/container-dependencies: "{nginx: [backend, frontend]}"
        run.googleapis.com/invoker-iam-disabled: 'true'
    spec:
      timeoutSeconds: "3600"
      containers:
        # Main container - Nginx
        - image: nginx:stable-alpine
          name: nginx
          ports:
            - containerPort: 8080
              name: http1
          volumeMounts:
            - name: nginx-conf-secret
              mountPath: /etc/nginx/conf.d/
              readOnly: true
            - name: site-verify-html
              mountPath: /usr/share/nginx/html/
              readOnly: true
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 2
            tcpSocket:
              port: 8080
        # Backend sidecar container
        - image: asia-northeast1-docker.pkg.dev/ai-agent-sample-1/ppp-registry/backend:__COMMIT_SHA__
          name: backend
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: GOOGLE_GENAI_USE_VERTEXAI
              value: "true"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "telemetry.googleapis.com:443"
            - name: FRONTEND_URL
              value: "https://ppp-jjoi5qw7aa-an.a.run.app"
            - name: API_BASE_URL
              value: "https://ppp-jjoi5qw7aa-an.a.run.app"
            - name: MCP_ENDPOINT_URL
              value: "http://localhost:8889"
            - name: RSS_FEED_RAG_CORPUS_ID
              value: "projects/ai-agent-sample-1/locations/us-central1/ragCorpora/2305843009213693952"
            - name: SESSION_SERVICE_URI
              value: "agentengine://1585944367997124608"
            - name: ARTIFACT_SERVICE_URI
              value: "gs://ai-agent-sample-1-agent-engine-bucket"
            - name: PORT
              value: "8888"
            - name: GOOGLE_CLOUD_PROJECT
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GOOGLE_CLOUD_PROJECT
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GOOGLE_CLIENT_ID
            - name: BACKEND_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: BACKEND_URL
            - name: ARTIFACT_BUCKET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: ARTIFACT_BUCKET
            - name: AGENT_ENGINE_ID
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: AGENT_ENGINE_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_CLOUD_LOCATION
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GOOGLE_CLOUD_LOCATION
            - name: GOOGLE_STORAGE_AUDIO_EXPORT_BUCKET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GOOGLE_STORAGE_AUDIO_EXPORT_BUCKET
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: SECRET_KEY

          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 2
            tcpSocket:
              port: 8888
        # MCP sidecar container
        - image: asia-northeast1-docker.pkg.dev/ai-agent-sample-1/ppp-registry/backend:__COMMIT_SHA__
          name: mcp
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: GOOGLE_GENAI_USE_VERTEXAI
              value: "true"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "telemetry.googleapis.com:443"
            - name: FRONTEND_URL
              value: "https://ppp-jjoi5qw7aa-an.a.run.app"
            - name: API_BASE_URL
              value: "https://ppp-jjoi5qw7aa-an.a.run.app"
            - name: MCP_ENDPOINT_URL
              value: "http://localhost:8889"
            - name: MCP_ENDPOINT_URL
              value: "http://localhost:8889"
            - name: RSS_FEED_RAG_CORPUS_ID
              value: "projects/ai-agent-sample-1/locations/us-central1/ragCorpora/2305843009213693952"
            - name: SESSION_SERVICE_URI
              value: "agentengine://1585944367997124608"
            - name: ARTIFACT_SERVICE_URI
              value: "gs://ai-agent-sample-1-agent-engine-bucket"
            - name: PORT
              value: "8889"
            - name: MCP_MODE
              value: "true"
            - name: GOOGLE_CLOUD_PROJECT
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GOOGLE_CLOUD_PROJECT
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GOOGLE_CLIENT_ID
            - name: BACKEND_URL
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: BACKEND_URL
            - name: ARTIFACT_BUCKET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: ARTIFACT_BUCKET
            - name: AGENT_ENGINE_ID
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: AGENT_ENGINE_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_CLOUD_LOCATION
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GOOGLE_CLOUD_LOCATION
            - name: GOOGLE_STORAGE_AUDIO_EXPORT_BUCKET
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: GOOGLE_STORAGE_AUDIO_EXPORT_BUCKET
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: SECRET_KEY

          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 2
            tcpSocket:
              port: 8888
        # Frontend sidecar container
        - image: asia-northeast1-docker.pkg.dev/ai-agent-sample-1/ppp-registry/frontend:__COMMIT_SHA__
          name: frontend
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: PORT
              value: "8881"
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 2
            tcpSocket:
              port: 8881
      volumes:
        - name: nginx-conf-secret
          secret:
            secretName: nginx-conf-secret
            items:
              - key: latest
                path: default.conf
        - name: site-verify-html
          secret:
            secretName: site-verify-html
            items:
              - key: latest
                path: google36f9c9056e4fb33e.html
