# Copyright 2025 Keisuke Tominaga a.k.a soundTricker
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import datetime
import os
from typing import Any, Dict  # Dict をインポート

import weatherapi
from google.adk.tools import FunctionTool
from weatherapi.api import APIsApi
from weatherapi.api_client import ApiClient


def get_daily_weather_forecast_by_coordinates(
    latitude: float,
    longitude: float,
    target_date_str: str, # 日付を文字列で受け取る (YYYY-MM-DD形式を想定)
    language_code: str = "ja",
) -> Dict[str, Any]:
    """
    指定された緯度、経度、および日付の天気予報を取得します。

    Args:
        latitude: 情報を取得したい地点の緯度。
        longitude: 情報を取得したい地点の経度。
        target_date_str: 天気予報を取得したい日付 (YYYY-MM-DD形式の文字列)。
        language_code: 結果の言語コード (例: "en", "ja")。デフォルトは "ja"。

    Returns:
        成功した場合は、指定された日の最高気温、最低気温、日中の天気の状態などを含む辞書と
        ステータス("status": "success")。
        指定された日付の予報が見つからない場合や失敗した場合は、
        エラーメッセージ("error")とステータス("status": "error") を含む辞書。

        例 (成功 典型的なキー):
        {
    "status": "success",
    "location": {
        "name": "Tokyo",
        "region": "Tokyo",
        "country": "Japan",
        "lat": 35.69,
        "lon": 139.692,
        "tz_id": "Asia/Tokyo",
        "localtime_epoch": 1749450143,
        "localtime": "2025-06-09 15: 22"
    },
    "current": {
        "last_updated_epoch": 1749449700,
        "last_updated": "2025-06-09 15: 15",
        "temp_c": 23.3,
        "temp_f": 73.9,
        "is_day": 1,
        "condition": {
            "text": "所により曇り",
            "icon": " //cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003
        },
        "wind_mph": 11.4,
        "wind_kph": 18.4,
        "wind_degree": 188,
        "wind_dir": "S",
        "pressure_mb": 1012.0,
        "pressure_in": 29.88,
        "precip_mm": 0.01,
        "precip_in": 0.0,
        "humidity": 69,
        "cloud": 75,
        "feelslike_c": 25.1,
        "feelslike_f": 77.1,
        "windchill_c": 24.3,
        "windchill_f": 75.7,
        "heatindex_c": 25.7,
        "heatindex_f": 78.3,
        "dewpoint_c": 16.6,
        "dewpoint_f": 61.9,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 2.3,
        "gust_mph": 13.1,
        "gust_kph": 21.1
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2025-06-10",
                "date_epoch": 1749513600,
                "day": {
                    "maxtemp_c": 21.3,
                    "maxtemp_f": 70.3,
                    "mintemp_c": 19.4,
                    "mintemp_f": 66.9,
                    "avgtemp_c": 20.3,
                    "avgtemp_f": 68.6,
                    "maxwind_mph": 6.9,
                    "maxwind_kph": 11.2,
                    "totalprecip_mm": 6.7,
                    "totalprecip_in": 0.26,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 7.3,
                    "avgvis_miles": 4.0,
                    "avghumidity": 85,
                    "daily_will_it_rain": 1,
                    "daily_chance_of_rain": 92,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "穏やかな雨",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
                        "code": 1189
                    },
                    "uv": 1.0
                },
                "astro": {
                    "sunrise": "04:25 AM",
                    "sunset": "06:57 PM",
                    "moonrise": "06:17 PM",
                    "moonset": "03:02 AM",
                    "moon_phase": "Waxing Gibbous",
                    "moon_illumination": 98,
                    "is_moon_up": 0,
                    "is_sun_up": 1
                },
                "hour": [
                    {
                        "time_epoch": 1749481200,
                        "time": "2025-06-10 00:00",
                        "temp_c": 19.4,
                        "temp_f": 66.9,
                        "is_day": 0,
                        "condition": {
                            "text": "霧雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 2.9,
                        "wind_kph": 4.7,
                        "wind_degree": 135,
                        "wind_dir": "SE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.89,
                        "precip_mm": 0.19,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 87,
                        "cloud": 94,
                        "feelslike_c": 19.4,
                        "feelslike_f": 66.9,
                        "windchill_c": 19.4,
                        "windchill_f": 66.9,
                        "heatindex_c": 19.4,
                        "heatindex_f": 66.9,
                        "dewpoint_c": 17.1,
                        "dewpoint_f": 62.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 3.9,
                        "gust_kph": 6.3,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1749484800,
                        "time": "2025-06-10 01:00",
                        "temp_c": 19.5,
                        "temp_f": 67.2,
                        "is_day": 0,
                        "condition": {
                            "text": "霧雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 2.7,
                        "wind_kph": 4.3,
                        "wind_degree": 146,
                        "wind_dir": "SSE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.89,
                        "precip_mm": 0.18,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 86,
                        "cloud": 100,
                        "feelslike_c": 19.6,
                        "feelslike_f": 67.2,
                        "windchill_c": 19.6,
                        "windchill_f": 67.2,
                        "heatindex_c": 19.6,
                        "heatindex_f": 67.2,
                        "dewpoint_c": 17.1,
                        "dewpoint_f": 62.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 3.6,
                        "gust_kph": 5.9,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1749488400,
                        "time": "2025-06-10 02:00",
                        "temp_c": 19.5,
                        "temp_f": 67.2,
                        "is_day": 0,
                        "condition": {
                            "text": "霧雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 2.7,
                        "wind_kph": 4.3,
                        "wind_degree": 102,
                        "wind_dir": "ESE",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.87,
                        "precip_mm": 0.33,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 86,
                        "cloud": 100,
                        "feelslike_c": 19.5,
                        "feelslike_f": 67.2,
                        "windchill_c": 19.5,
                        "windchill_f": 67.2,
                        "heatindex_c": 19.5,
                        "heatindex_f": 67.2,
                        "dewpoint_c": 17.2,
                        "dewpoint_f": 62.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 3.6,
                        "gust_kph": 5.9,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1749492000,
                        "time": "2025-06-10 03:00",
                        "temp_c": 19.5,
                        "temp_f": 67.2,
                        "is_day": 0,
                        "condition": {
                            "text": "近くで所により雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 75,
                        "wind_dir": "ENE",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.86,
                        "precip_mm": 0.12,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 87,
                        "cloud": 88,
                        "feelslike_c": 19.5,
                        "feelslike_f": 67.2,
                        "windchill_c": 19.5,
                        "windchill_f": 67.2,
                        "heatindex_c": 19.5,
                        "heatindex_f": 67.2,
                        "dewpoint_c": 17.2,
                        "dewpoint_f": 63.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.3,
                        "gust_kph": 6.8,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1749495600,
                        "time": "2025-06-10 04:00",
                        "temp_c": 19.6,
                        "temp_f": 67.3,
                        "is_day": 0,
                        "condition": {
                            "text": "近くで所により雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 3.1,
                        "wind_kph": 5.0,
                        "wind_degree": 60,
                        "wind_dir": "ENE",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.86,
                        "precip_mm": 0.11,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 86,
                        "cloud": 88,
                        "feelslike_c": 19.6,
                        "feelslike_f": 67.3,
                        "windchill_c": 19.6,
                        "windchill_f": 67.3,
                        "heatindex_c": 19.6,
                        "heatindex_f": 67.3,
                        "dewpoint_c": 17.2,
                        "dewpoint_f": 63.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.3,
                        "gust_kph": 6.8,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1749499200,
                        "time": "2025-06-10 05:00",
                        "temp_c": 19.8,
                        "temp_f": 67.6,
                        "is_day": 1,
                        "condition": {
                            "text": "近くで所により雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 2.5,
                        "wind_kph": 4.0,
                        "wind_degree": 45,
                        "wind_dir": "NE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.87,
                        "precip_mm": 0.02,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 85,
                        "cloud": 84,
                        "feelslike_c": 19.8,
                        "feelslike_f": 67.6,
                        "windchill_c": 19.8,
                        "windchill_f": 67.6,
                        "heatindex_c": 19.8,
                        "heatindex_f": 67.6,
                        "dewpoint_c": 17.2,
                        "dewpoint_f": 62.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 75,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 3.4,
                        "gust_kph": 5.4,
                        "uv": 0.0
                    },
                    {
                        "time_epoch": 1749502800,
                        "time": "2025-06-10 06:00",
                        "temp_c": 20.0,
                        "temp_f": 68.1,
                        "is_day": 1,
                        "condition": {
                            "text": "曇り",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                            "code": 1006
                        },
                        "wind_mph": 2.7,
                        "wind_kph": 4.3,
                        "wind_degree": 46,
                        "wind_dir": "NE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.88,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 83,
                        "cloud": 72,
                        "feelslike_c": 20.1,
                        "feelslike_f": 68.1,
                        "windchill_c": 20.1,
                        "windchill_f": 68.1,
                        "heatindex_c": 20.1,
                        "heatindex_f": 68.1,
                        "dewpoint_c": 17.1,
                        "dewpoint_f": 62.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 3.7,
                        "gust_kph": 5.9,
                        "uv": 0.2
                    },
                    {
                        "time_epoch": 1749506400,
                        "time": "2025-06-10 07:00",
                        "temp_c": 20.5,
                        "temp_f": 68.8,
                        "is_day": 1,
                        "condition": {
                            "text": "曇り",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                            "code": 1006
                        },
                        "wind_mph": 2.5,
                        "wind_kph": 4.0,
                        "wind_degree": 69,
                        "wind_dir": "ENE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.88,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 81,
                        "cloud": 85,
                        "feelslike_c": 20.5,
                        "feelslike_f": 68.8,
                        "windchill_c": 20.5,
                        "windchill_f": 68.8,
                        "heatindex_c": 20.5,
                        "heatindex_f": 68.8,
                        "dewpoint_c": 17.2,
                        "dewpoint_f": 62.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 3.3,
                        "gust_kph": 5.3,
                        "uv": 0.7
                    },
                    {
                        "time_epoch": 1749510000,
                        "time": "2025-06-10 08:00",
                        "temp_c": 20.4,
                        "temp_f": 68.7,
                        "is_day": 1,
                        "condition": {
                            "text": "霧雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                            "code": 1153
                        },
                        "wind_mph": 2.7,
                        "wind_kph": 4.3,
                        "wind_degree": 75,
                        "wind_dir": "ENE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.88,
                        "precip_mm": 0.52,
                        "precip_in": 0.02,
                        "snow_cm": 0.0,
                        "humidity": 82,
                        "cloud": 85,
                        "feelslike_c": 20.4,
                        "feelslike_f": 68.7,
                        "windchill_c": 20.4,
                        "windchill_f": 68.7,
                        "heatindex_c": 20.4,
                        "heatindex_f": 68.7,
                        "dewpoint_c": 17.2,
                        "dewpoint_f": 62.9,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 3.6,
                        "gust_kph": 5.9,
                        "uv": 1.6
                    },
                    {
                        "time_epoch": 1749513600,
                        "time": "2025-06-10 09:00",
                        "temp_c": 20.4,
                        "temp_f": 68.8,
                        "is_day": 1,
                        "condition": {
                            "text": "近くで所により雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 2.2,
                        "wind_kph": 3.6,
                        "wind_degree": 74,
                        "wind_dir": "ENE",
                        "pressure_mb": 1012.0,
                        "pressure_in": 29.87,
                        "precip_mm": 0.05,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 82,
                        "cloud": 100,
                        "feelslike_c": 20.4,
                        "feelslike_f": 68.8,
                        "windchill_c": 20.4,
                        "windchill_f": 68.8,
                        "heatindex_c": 20.4,
                        "heatindex_f": 68.8,
                        "dewpoint_c": 17.4,
                        "dewpoint_f": 63.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 89,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 3.0,
                        "gust_kph": 4.8,
                        "uv": 4.3
                    },
                    {
                        "time_epoch": 1749517200,
                        "time": "2025-06-10 10:00",
                        "temp_c": 20.7,
                        "temp_f": 69.3,
                        "is_day": 1,
                        "condition": {
                            "text": "近くで所により雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 2.7,
                        "wind_kph": 4.3,
                        "wind_degree": 151,
                        "wind_dir": "SSE",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.87,
                        "precip_mm": 0.07,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 81,
                        "cloud": 100,
                        "feelslike_c": 20.7,
                        "feelslike_f": 69.3,
                        "windchill_c": 20.7,
                        "windchill_f": 69.3,
                        "heatindex_c": 20.7,
                        "heatindex_f": 69.3,
                        "dewpoint_c": 17.3,
                        "dewpoint_f": 63.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 3.6,
                        "gust_kph": 5.8,
                        "uv": 3.8
                    },
                    {
                        "time_epoch": 1749520800,
                        "time": "2025-06-10 11:00",
                        "temp_c": 21.3,
                        "temp_f": 70.3,
                        "is_day": 1,
                        "condition": {
                            "text": "本曇り",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                            "code": 1009
                        },
                        "wind_mph": 4.0,
                        "wind_kph": 6.5,
                        "wind_degree": 153,
                        "wind_dir": "SSE",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.86,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 78,
                        "cloud": 100,
                        "feelslike_c": 21.3,
                        "feelslike_f": 70.3,
                        "windchill_c": 21.3,
                        "windchill_f": 70.3,
                        "heatindex_c": 24.3,
                        "heatindex_f": 75.8,
                        "dewpoint_c": 17.3,
                        "dewpoint_f": 63.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.2,
                        "gust_kph": 8.4,
                        "uv": 3.4
                    },
                    {
                        "time_epoch": 1749524400,
                        "time": "2025-06-10 12:00",
                        "temp_c": 21.3,
                        "temp_f": 70.3,
                        "is_day": 1,
                        "condition": {
                            "text": "近くで所により雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 156,
                        "wind_dir": "SSE",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.86,
                        "precip_mm": 0.07,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 78,
                        "cloud": 100,
                        "feelslike_c": 21.3,
                        "feelslike_f": 70.3,
                        "windchill_c": 21.3,
                        "windchill_f": 70.3,
                        "heatindex_c": 24.3,
                        "heatindex_f": 75.8,
                        "dewpoint_c": 17.3,
                        "dewpoint_f": 63.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.1,
                        "gust_kph": 11.4,
                        "uv": 3.4
                    },
                    {
                        "time_epoch": 1749528000,
                        "time": "2025-06-10 13:00",
                        "temp_c": 21.1,
                        "temp_f": 70.0,
                        "is_day": 1,
                        "condition": {
                            "text": "近くで所により雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "wind_mph": 5.1,
                        "wind_kph": 8.3,
                        "wind_degree": 166,
                        "wind_dir": "SSE",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.85,
                        "precip_mm": 0.13,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 80,
                        "cloud": 100,
                        "feelslike_c": 21.1,
                        "feelslike_f": 70.0,
                        "windchill_c": 21.1,
                        "windchill_f": 70.0,
                        "heatindex_c": 24.3,
                        "heatindex_f": 75.7,
                        "dewpoint_c": 17.5,
                        "dewpoint_f": 63.6,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.8,
                        "gust_kph": 10.9,
                        "uv": 2.4
                    },
                    {
                        "time_epoch": 1749531600,
                        "time": "2025-06-10 14:00",
                        "temp_c": 20.7,
                        "temp_f": 69.2,
                        "is_day": 1,
                        "condition": {
                            "text": "霧雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                            "code": 1153
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 177,
                        "wind_dir": "S",
                        "pressure_mb": 1011.0,
                        "pressure_in": 29.84,
                        "precip_mm": 0.74,
                        "precip_in": 0.03,
                        "snow_cm": 0.0,
                        "humidity": 84,
                        "cloud": 100,
                        "feelslike_c": 20.7,
                        "feelslike_f": 69.2,
                        "windchill_c": 20.7,
                        "windchill_f": 69.2,
                        "heatindex_c": 20.7,
                        "heatindex_f": 69.2,
                        "dewpoint_c": 17.8,
                        "dewpoint_f": 64.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 7.7,
                        "gust_kph": 12.5,
                        "uv": 1.4
                    },
                    {
                        "time_epoch": 1749535200,
                        "time": "2025-06-10 15:00",
                        "temp_c": 20.4,
                        "temp_f": 68.7,
                        "is_day": 1,
                        "condition": {
                            "text": "弱い雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 5.6,
                        "wind_kph": 9.0,
                        "wind_degree": 173,
                        "wind_dir": "S",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.83,
                        "precip_mm": 1.1,
                        "precip_in": 0.04,
                        "snow_cm": 0.0,
                        "humidity": 87,
                        "cloud": 100,
                        "feelslike_c": 20.4,
                        "feelslike_f": 68.7,
                        "windchill_c": 20.4,
                        "windchill_f": 68.7,
                        "heatindex_c": 20.4,
                        "heatindex_f": 68.7,
                        "dewpoint_c": 18.1,
                        "dewpoint_f": 64.6,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 7.5,
                        "gust_kph": 12.0,
                        "uv": 0.9
                    },
                    {
                        "time_epoch": 1749538800,
                        "time": "2025-06-10 16:00",
                        "temp_c": 20.1,
                        "temp_f": 68.2,
                        "is_day": 1,
                        "condition": {
                            "text": "弱い雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
                            "code": 1183
                        },
                        "wind_mph": 5.6,
                        "wind_kph": 9.0,
                        "wind_degree": 188,
                        "wind_dir": "S",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.83,
                        "precip_mm": 2.06,
                        "precip_in": 0.08,
                        "snow_cm": 0.0,
                        "humidity": 90,
                        "cloud": 100,
                        "feelslike_c": 20.1,
                        "feelslike_f": 68.2,
                        "windchill_c": 20.1,
                        "windchill_f": 68.2,
                        "heatindex_c": 20.1,
                        "heatindex_f": 68.2,
                        "dewpoint_c": 18.4,
                        "dewpoint_f": 65.0,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 9.0,
                        "vis_miles": 5.0,
                        "gust_mph": 7.6,
                        "gust_kph": 12.3,
                        "uv": 0.8
                    },
                    {
                        "time_epoch": 1749542400,
                        "time": "2025-06-10 17:00",
                        "temp_c": 20.3,
                        "temp_f": 68.5,
                        "is_day": 1,
                        "condition": {
                            "text": "霧雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                            "code": 1153
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 192,
                        "wind_dir": "SSW",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.83,
                        "precip_mm": 0.19,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 89,
                        "cloud": 100,
                        "feelslike_c": 20.3,
                        "feelslike_f": 68.5,
                        "windchill_c": 20.3,
                        "windchill_f": 68.5,
                        "heatindex_c": 20.3,
                        "heatindex_f": 68.5,
                        "dewpoint_c": 18.5,
                        "dewpoint_f": 65.3,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 7.3,
                        "gust_kph": 11.8,
                        "uv": 0.2
                    },
                    {
                        "time_epoch": 1749546000,
                        "time": "2025-06-10 18:00",
                        "temp_c": 20.4,
                        "temp_f": 68.8,
                        "is_day": 1,
                        "condition": {
                            "text": "霧雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                            "code": 1153
                        },
                        "wind_mph": 6.3,
                        "wind_kph": 10.1,
                        "wind_degree": 175,
                        "wind_dir": "S",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.83,
                        "precip_mm": 0.29,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 89,
                        "cloud": 100,
                        "feelslike_c": 20.4,
                        "feelslike_f": 68.8,
                        "windchill_c": 20.4,
                        "windchill_f": 68.8,
                        "heatindex_c": 20.4,
                        "heatindex_f": 68.8,
                        "dewpoint_c": 18.6,
                        "dewpoint_f": 65.4,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 8.5,
                        "gust_kph": 13.8,
                        "uv": 0.0
                    },
                    {
                        "time_epoch": 1749549600,
                        "time": "2025-06-10 19:00",
                        "temp_c": 20.5,
                        "temp_f": 68.8,
                        "is_day": 0,
                        "condition": {
                            "text": "近くで所により雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 6.9,
                        "wind_kph": 11.2,
                        "wind_degree": 193,
                        "wind_dir": "SSW",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.83,
                        "precip_mm": 0.03,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 90,
                        "cloud": 100,
                        "feelslike_c": 20.5,
                        "feelslike_f": 68.8,
                        "windchill_c": 20.5,
                        "windchill_f": 68.8,
                        "heatindex_c": 20.5,
                        "heatindex_f": 68.8,
                        "dewpoint_c": 18.7,
                        "dewpoint_f": 65.7,
                        "will_it_rain": 0,
                        "chance_of_rain": 67,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.6,
                        "gust_kph": 15.4,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1749553200,
                        "time": "2025-06-10 20:00",
                        "temp_c": 20.6,
                        "temp_f": 69.0,
                        "is_day": 0,
                        "condition": {
                            "text": "近くで所により雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 6.0,
                        "wind_kph": 9.7,
                        "wind_degree": 190,
                        "wind_dir": "S",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.83,
                        "precip_mm": 0.06,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 89,
                        "cloud": 100,
                        "feelslike_c": 20.6,
                        "feelslike_f": 69.0,
                        "windchill_c": 20.6,
                        "windchill_f": 69.0,
                        "heatindex_c": 20.6,
                        "heatindex_f": 69.0,
                        "dewpoint_c": 18.8,
                        "dewpoint_f": 65.8,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.5,
                        "gust_kph": 13.6,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1749556800,
                        "time": "2025-06-10 21:00",
                        "temp_c": 20.7,
                        "temp_f": 69.3,
                        "is_day": 0,
                        "condition": {
                            "text": "近くで所により雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 5.4,
                        "wind_kph": 8.6,
                        "wind_degree": 193,
                        "wind_dir": "SSW",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.82,
                        "precip_mm": 0.1,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 90,
                        "cloud": 100,
                        "feelslike_c": 20.7,
                        "feelslike_f": 69.3,
                        "windchill_c": 20.7,
                        "windchill_f": 69.3,
                        "heatindex_c": 20.7,
                        "heatindex_f": 69.3,
                        "dewpoint_c": 19.0,
                        "dewpoint_f": 66.2,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.5,
                        "gust_kph": 12.1,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1749560400,
                        "time": "2025-06-10 22:00",
                        "temp_c": 20.8,
                        "temp_f": 69.4,
                        "is_day": 0,
                        "condition": {
                            "text": "霧雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                            "code": 1153
                        },
                        "wind_mph": 4.0,
                        "wind_kph": 6.5,
                        "wind_degree": 226,
                        "wind_dir": "SW",
                        "pressure_mb": 1010.0,
                        "pressure_in": 29.82,
                        "precip_mm": 0.32,
                        "precip_in": 0.01,
                        "snow_cm": 0.0,
                        "humidity": 91,
                        "cloud": 95,
                        "feelslike_c": 20.8,
                        "feelslike_f": 69.4,
                        "windchill_c": 20.8,
                        "windchill_f": 69.4,
                        "heatindex_c": 20.8,
                        "heatindex_f": 69.4,
                        "dewpoint_c": 19.2,
                        "dewpoint_f": 66.5,
                        "will_it_rain": 1,
                        "chance_of_rain": 100,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 2.0,
                        "vis_miles": 1.0,
                        "gust_mph": 5.8,
                        "gust_kph": 9.4,
                        "uv": 0
                    },
                    {
                        "time_epoch": 1749564000,
                        "time": "2025-06-10 23:00",
                        "temp_c": 20.9,
                        "temp_f": 69.6,
                        "is_day": 0,
                        "condition": {
                            "text": "近くで所により雨",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                            "code": 1063
                        },
                        "wind_mph": 3.6,
                        "wind_kph": 5.8,
                        "wind_degree": 226,
                        "wind_dir": "SW",
                        "pressure_mb": 1009.0,
                        "pressure_in": 29.8,
                        "precip_mm": 0.03,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 90,
                        "cloud": 76,
                        "feelslike_c": 20.9,
                        "feelslike_f": 69.6,
                        "windchill_c": 20.9,
                        "windchill_f": 69.6,
                        "heatindex_c": 20.9,
                        "heatindex_f": 69.6,
                        "dewpoint_c": 19.3,
                        "dewpoint_f": 66.7,
                        "will_it_rain": 1,
                        "chance_of_rain": 80,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 5.2,
                        "gust_kph": 8.4,
                        "uv": 0
                    }
                ]
            }
        ]
    }
}
    """

    config = weatherapi.configuration.Configuration()
    config.api_key = {"key": os.environ.get("WEATHER_API_KEY")}
    api_instance = APIsApi(ApiClient(config))

    try:
        target_date = datetime.datetime.strptime(target_date_str, "%Y-%m-%d").date()
    except ValueError:
        return {
            "error": "日付の形式が無効です。YYYY-MM-DD形式で指定してください。",
            "status": "error",
        }

    response = api_instance.forecast_weather(q=f"{latitude},{longitude}", days=1, dt=target_date, lang=language_code, aqi="no", alerts="no")
    response["status"] = "success"
    return response


# ADKのFunctionToolとしてラップ
weather_tool = FunctionTool(
    func=get_daily_weather_forecast_by_coordinates,
    # name と description はdocstringから自動生成されるため、明示的な指定は通常不要
)
